# themes from https://github.com/alacritty/alacritty-theme

# import = ["/Users/mischa/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 25

[font.normal]
family = "Hack Nerd Font"

# Colors (Gruvbox Material Medium Dark)

# Default colors
[colors.primary]
background = '#282828'
foreground = '#d4be98'
